version: 2

sources:
  - name: ff_anilist
    description: Fluffy Folks data taken from Anilist
    schema: main
    tables:
      - name: users
      - name: lists_2022 # initial lists
      - name: favourites
      - name: raw_lists
      - name: score_mapping
      # - name: media_details
